### ISSUE TITLE
Getting `There must be an exit code from a previous step.` error

### ISSUE THREAD

**Issue by pjangam** [robburger/terraform-pr-commenter#11]
My workflow looks like this

```
      - run: |
          terraform init
          terraform plan -out tfplan
        id: plan
      - uses: robburger/terraform-pr-commenter@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commenter_type: plan
          commenter_input: ${{ format('{0}{1}', steps.plan.outputs.stdout, steps.plan.outputs.stderr) }}
          commenter_exitcode: ${{ steps.plan.outputs.exitcode }}
```

Earlier I was using Makefile, I thought if it is doing something with exit code, So I had replaced `make plan` by the current multiline command which does `terraform init` and `terraform plan` but it doesn't seem to solve the issue.

Terraform version I'm using is 0.14.10

```
- uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.10
          terraform_wrapper: false
```
