### ISSUE TITLE
Add working-directory to the comment

### ISSUE THREAD

**Issue by wolverian** [robburger/terraform-pr-commenter#17]
Thank you for the great action! We're running it in production now. 🙂

I have a feature request that would help us: we're running this action for a bunch of modules in one repo, i.e. our repo looks something like this:

```
root
- vpc
- dns
- eks
- ...etc...
```

We use an Actions matrix to run the same steps for each directory. This works! 🎉 However, the comment for each init/plan/apply doesn't indicate which module it came from:

<img width="937" alt="Screenshot 2021-06-29 at 10 42 26" src="https://user-images.githubusercontent.com/42124/123757488-b5ca7280-d8c6-11eb-8d50-a25ad21210f9.png">

This could be fixed by adding the working directory to the message, so it would be e.g. "<directory>: Terraform <action> <result> for workspace <workspace>". Another option would be to add the directory to `commenter_input`, but I haven't tried this yet, as I've assumed that argument should contain only output from Terraform itself.

Does this sound like a sensible feature? Thank you!

**Comment by robburger** [comment]
@wolverian - sorry for the delay, and yes, excellent suggestion!

I recently ran into this problem myself with comments not being deleted due to the title lookup in a matrix run, but the folder problem is also relevant.

**Comment by MPV** [comment]
As inspiration, https://github.com/iStreamPlanet/github-actions/tree/main/terraform-actions does (or I should say "did", that action seems non-maintained nowadays) the equivalent with a working directory input to the action.

Whichever of the suggested solutions above sound promising (and would be what I'd need in order to switch from iStreamPlanet into this action). ❤️

**Comment by marcellovictorino** [comment]
Great suggestion @MPV 
As a workaround, I've been using the `TF_WORKSPACE` variable to keep track of environment and working directory:

```yaml
- name: >
    Post Plan >> Env: ${{ matrix.project.env }} | Dir: ${{ matrix.project.dir }}
  if: always() && github.ref != 'refs/heads/master' && (steps.plan.outcome == 'success' || steps.plan.outcome == 'failure')
  uses: robburger/terraform-pr-commenter@v1
  env:
    TF_WORKSPACE: ${{ format('Env= {0} | Dir= {1}', matrix.project.env, matrix.project.dir) }}
  with:
    commenter_type: plan
    commenter_input: ${{ format('{0}{1}', steps.plan.outputs.stdout, steps.plan.outputs.stderr) }}
    commenter_exitcode: ${{ steps.plan.outputs.exitcode }}
```

Which looks like this. Not great... not terrible...

![image](https://user-images.githubusercontent.com/18636680/140802621-f76e015d-394a-4d43-bf70-670773163ff7.png)

> **:warning:** Although, I noticed the action sometimes updates the wrong comment, removing a valid one.
