### ISSUE TITLE
Comment update removes the wrong comment

### ISSUE THREAD

**Issue by marcellovictorino** [robburger/terraform-pr-commenter#23]
This is a great action. Thanks for sharing!

In order to provide a bit more context when running on multiple working directories and environments, I've been using a workaround. Injecting the values of interest into the `TF_WORKSPACE` env variable.

Which works 👍 

```yaml
- name: >
    Post Plan >> Env: ${{ matrix.project.env }} | Dir: ${{ matrix.project.dir }}
  if: always() && github.ref != 'refs/heads/master' && (steps.plan.outcome == 'success' || steps.plan.outcome == 'failure')
  uses: robburger/terraform-pr-commenter@v1
  env:
    TF_WORKSPACE: ${{ format('Env= {0} | Dir= {1}', matrix.project.env, matrix.project.dir) }}
  with:
    commenter_type: plan
    commenter_input: ${{ format('{0}{1}', steps.plan.outputs.stdout, steps.plan.outputs.stderr) }}
    commenter_exitcode: ${{ steps.plan.outputs.exitcode }}
```
![image](https://user-images.githubusercontent.com/18636680/140803444-2799df44-8740-437c-aa09-db5fd2d35b93.png)

---
But I noticed that, sometimes, the action incorrectly identifies an "already existing" comment and decides to update it.
For example, I have 9 different `working-directories` / `env`. But only get 5 PR comments

@robburger Any ideas?
How exactly is the "uniqueness" of a comment defined?
I imagined that, by adding more detail to the TF_WORKSPACE, it would make it more accurate.
