### ISSUE TITLE
Please add an option input to allow or disallow PR comment overwrite

### ISSUE THREAD

**Issue by Pwd9000-ML** [robburger/terraform-pr-commenter#28]
Can an additional (optional) input be created e.g.:

```yml
  allow_pr_override:
    description: '(Optional) Allow existing comments on PR to be overridden.'
    required: false
    type: boolean
    default: true 
```

The reason this would be handy is because I do automated tests on a single workspace "default", but my tests involves using terraform plan, to plan and apply a build, and then after on the same PR I also do a terraform plan --destroy and then apply a destroy.

Because my initial plan which shows the build, the second plan (destroy plan) overrides the build plan on the PR, I would like this not to happen as I want to see both comments on the same PR for my `build plan` as well as my `destroy plan` as the test involves a build apply plan as well as a destroy apply plan.

The build plan will be commented as expected, but when my workflow reaches the destroy plan step, the existing build plan comment will be overriden and thus I end up only seeing the destroy plan on the PR comments.

I want this override to be configurable on the inputs on this action if possible. if the setting is false, I want the action to just add another comment on the same PR, and if the setting is true, it can override:

![image](https://user-images.githubusercontent.com/44137582/153405785-47d2ae53-8d60-4517-95f6-de49dc79d0ca.png)

At the moment it only and always will override.
