### ISSUE TITLE
Error: Argument list too long

### ISSUE THREAD

**Issue by MattiPuolitaivalGKGAB** [robburger/terraform-pr-commenter#6]
Hi!

First of all, thanks for the great tool. Been using it for few days and really digging it.

I'm trying to publish a plan output of a larger environment, but I get an error "Error: Argument list too long". The  plan output is around ~2800 rows long.

**Comment by robburger** [comment]
Hey @MattiPuolitaivalGKGAB - sorry it's taken so long to get to this issue...it was an interesting one to investigate!

I've just opened an issue https://github.com/actions/virtual-environments/issues/3257 to see if there's a possibility of changing the underlying GitHub Actions VM.

Unfortunately, if that can't be done, your only option would be to use a self-hosted runner with the stack size bumped up.

**Comment by nohhhon** [comment]
SAM;storage allocation method; command ultra prompt;exe?

**Comment by Fresa** [comment]
According to [this post](https://github.community/t/maximum-length-for-the-comment-body-in-issues-and-pr/148867) the maximum number of characters in a PR comment is 65536.

I have solved it by always truncating the plan before trying to post it.
```
- name: Format plan
  id: format-plan
  run: |
    plan=$(cat <<'EOF'
    ${{ format('{0}{1}', steps.plan.outputs.stdout, steps.plan.outputs.stderr) }}
    EOF
    )
    echo "PLAN<<EOF" >> $GITHUB_ENV
    echo "${plan:0:65536}" >> $GITHUB_ENV
    echo "EOF" >> $GITHUB_ENV
```
Would be nice if the action would solve that in some nice and informant way :)

**Comment by robburger** [comment]
@MattiPuolitaivalGKGAB the issue linked above has been merged in the `actions` repo and new GitHub VM runners have been rolled out this last week.

While I have not tested this, you should be able to pass in a much longer plan now - up to ~16MB of text. The PR commenter will still truncate it anyway here: https://github.com/robburger/terraform-pr-commenter/blob/c06d8f2ef864a84d4e7809af0946139faed59469/entrypoint.sh#L188 because of the GitHub comment limit...but it should not cause the build to fail anymore.

**Comment by MattiPuolitaivalGKGAB** [comment]
Excellent, thanks @robburger!

**Comment by JRo-connyun** [comment]
Hi @robburger,

we unfortunately also ran into this problem today with our plan output of ~3500 rows, which made the job fail. We are running on `ubuntu-latest` machines and use version `1.4.0` of the terraform-pr-commenter.

Did we overlook something?

**Comment by robburger** [comment]
Hi @JRo-connyun - I don't think you missed anything. Unfortunately, your plan is probably over the new 16MB input limit on the Actions runner instances (or they're not yet fully rolled out...)

In this case, the best option would be to add a new step after the `plan` to truncate before sending to the commenter step, like @Fresa has above. With that step above, a new `PLAN` [environment variable](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable) becomes available to all steps.

A simpler way might be to use the [`set-output`](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter) workflow function. e.g.:
```yaml
- name: Terraform Plan
  id: plan
  run: terraform plan -out workspace.plan

- name: Truncate Plan
  id: truncate-plan
  run: echo "::set-output name=plan::${${{ format('{0}{1}', steps.plan.outputs.stdout, steps.plan.outputs.stderr) }}:0:65536}"

- name: Post Plan
  if: ...
  uses: robburger/terraform-pr-commenter@v1
  with:
    commenter_type: plan
    commenter_input: ${{ steps.truncate-plan.outputs.plan }}
    commenter_exitcode: ${{ steps.plan.outputs.exitcode }}
```
☝️ Note: I haven't (yet) tested if this syntax is correct, or will work...

I will test it this weekend and add to the readme. Thanks for raising this again!

**Comment by menzenski** [comment]
@robburger for what it's worth, the above does not work for me. The action exits with 

```
Error: The template is not valid. System.InvalidOperationException: Maximum object size exceeded
   at GitHub.DistributedTask.ObjectTemplating.TemplateMemory.AddBytes(Int32 bytes)
   at GitHub.DistributedTask.ObjectTemplating.TemplateMemory.AddBytes(TemplateToken value, Boolean traverse)
   at GitHub.DistributedTask.ObjectTemplating.TemplateUnraveler.AllowScalar(Boolean expand, ScalarToken& scalar)
   at GitHub.DistributedTask.ObjectTemplating.TemplateEvaluator.Evaluate(DefinitionInfo definition)
   at GitHub.DistributedTask.ObjectTemplating.TemplateEvaluator.HandleMappingWithAllLooseProperties(DefinitionInfo mappingDefinition, DefinitionInfo keyDefinition, DefinitionInfo valueDefinition, MappingToken mapping)
   at GitHub.DistributedTask.ObjectTemplating.TemplateEvaluator.Evaluate(DefinitionInfo definition)
   at GitHub.DistributedTask.ObjectTemplating.TemplateEvaluator.Evaluate(TemplateContext context, String type, TemplateToken template, Int32 removeBytes, Nullable`1 fileId, Boolean omitHeader)
```

I am using these steps:

```yml
    - name: Terraform Plan
      id: plan
      if: github.event_name == 'pull_request'
      run: terraform plan

    - name: Truncate Plan
      id: truncate-plan
      run: echo "::set-output name=plan::${${{ format('{0}{1}', steps.plan.outputs.stdout, steps.plan.outputs.stderr) }}:0:65536}"

    - name: Post Plan
      if: always() && github.ref != 'refs/heads/main' && (steps.plan.outcome == 'success' || steps.plan.outcome == 'failure')
      uses: robburger/terraform-pr-commenter@v1
      with:
        commenter_type: plan
        commenter_input: ${{ steps.truncate-plan.outputs.plan }}
        commenter_exitcode: ${{ steps.plan.outputs.exitcode }}

**Comment by mortizTAG** [comment]
Hi,
I am facing same exact situation, what has the final fix?
Thanks in advance

**Comment by mortizTAG** [comment]
> According to [this post](https://github.community/t/maximum-length-for-the-comment-body-in-issues-and-pr/148867) the maximum number of characters in a PR comment is 65536.
> 
> I have solved it by always truncating the plan before trying to post it.
> 
> ```
> - name: Format plan
>   id: format-plan
>   run: |
>     plan=$(cat <<'EOF'
>     ${{ format('{0}{1}', steps.plan.outputs.stdout, steps.plan.outputs.stderr) }}
>     EOF
>     )
>     echo "PLAN<<EOF" >> $GITHUB_ENV
>     echo "${plan:0:65536}" >> $GITHUB_ENV
>     echo "EOF" >> $GITHUB_ENV
> ```
This worked for me.

**Comment by aditya-enthu** [comment]
Hello @menzenski, @robburger 

Greetings.

Trying this fix but it doesn't seem to trim the plan.
https://github.com/robburger/terraform-pr-commenter/issues/6#issuecomment-976977894

```
Run echo "::set-output name=plan::${
/home/runner/work/_temp/0d83a182-527c-48f2-aa62-e77b6a733bee.sh: line 236: syntax error near unexpected token `('
Error: Process completed with exit code 2.
```

Using exactly same steps:
```
      - run: terraform plan -input=false -refresh=false
        id: plan-color
        continue-on-error: true

      - name: Truncate Plan
        id: truncate-plan
        run: echo "::set-output name=plan::${${{ format('{0}{1}', steps.plan-color.outputs.stdout, steps.plan-color.outputs.stderr) }}:0:65536}"

      - name: Post Plan PR comment
        if: steps.plan-color.outcome == 'success' || steps.plan-color.outcome == 'failure'
        uses: robburger/terraform-pr-commenter@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
        with:
          commenter_type: plan
          commenter_input: ${{ steps.truncate-plan.outputs.plan }}
          commenter_exitcode: ${{ steps.plan-color.outputs.exitcode }}
```
